<div class="modal fade" id="cadastrarModal" tabindex="-1" role="dialog" aria-labelledby="cadastrarModalLabel" aria-hidden="true" data-backdrop="static">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header alert-info">
				<h3 class="modal-title" id="cadastrarModalLabel">Nova Categoria
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</h3>
			</div>
      <form>
        <div class="modal-body">
          <div class="form-group">
            <label class="col-form-label">Tipo:</label>
            <select class="form-control">            
            </select>
          </div>
          <div class="form-group">
            <label for="descricao" class="col-form-label">Descrição:</label>
            <input type="text" class="form-control" id="descricao">
          </div>
        </div>
        <div class="modal-footer">
          <input type="submit" value="Gravar" class="btn btn-primary">
        </div>
      </form>
		</div>
	</div>
</div>

<script>
    //$('#cadastrarModal').on('show.bs.modal', function (event) {
		//var button = $(event.relatedTarget); // Button that triggered the modal
		//var recipient = button.data('whatever'); // Extract info from data-* attributes
		// If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
		// Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
		//var modal = $(this);
		//modal.find('.modal-title').text(recipient + ' Categoria');
		//modal.find('.modal-body input').val(recipient);
    });
</script>