<!-- Modal -->
<div id="cadastrarModal" class="modal fade" data-backdrop="static">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header alert-info">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title" id="cadastrarModalLabel">Cadastrar Categoria</h4>
            </div>
            <form method="post" action="<?php echo $this->url('rotacategoria', [
                    'action' => 'cadastrar'
                ]); ?>">
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-form-label">Tipo:</label>
                        <select name="tipo" id="tipo" class="form-control" required>
                            <option value=""></option>
                            <option value="despesa">Despesa</option>
                            <option value="receita">Receita</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="nome" class="col-form-label">Nome:</label>
                        <input type="text" class="form-control" id="nome" name="nome" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" value="Gravar" class="btn btn-primary">
                </div>
            </form>

        </div>

    </div>
</div>
<script>
    $('#cadastrarModal').on('show.bs.modal', function (event) {
        $('#tipo').val("");
        $('#nome').val("");
    });
</script>