<div class="modal fade" id="editarModal" tabindex="-1" role="dialog" aria-labelledby="editarModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header alert-info">
                <h3 class="modal-title" id="editarModalLabel">Editar Categoria</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                
            </div>
            <form method="post" action="<?php echo $this->url('rotacategoria', [
                        'action' => 'editar'
                    ]); ?>">
                <div class="modal-body">
                    <div class="form-group">
                        <input type="hidden" class="form-control" id="id" name="id">
                        <label class="col-form-label">Tipo:</label>
                        <select name="tipoEdicao" id="tipoEdicao" class="form-control" required>
                            <option value=""></option>
                            <option value="despesa">Despesa</option>
                            <option value="receita">Receita</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="nomeEdicao" class="col-form-label">Nome:</label>
                        <input type="text" class="form-control" id="nomeEdicao" name="nomeEdicao" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" value="Gravar" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $('#editarModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget); // Button that triggered the modal
        var id = button.data('id'); // Extract info from data-* attributes
        $('#id').val(id);
        $.ajax({
            url: "<?php echo $this->url('rotacategoria', [
                        'action' => 'buscar'
                    ]); ?>",
            type: "POST",
            data: {id: id},
            dataType: "json"

        }).done(function(resposta) {
            $('#tipoEdicao').val(resposta.data[0].tipo);
            $('#nomeEdicao').val(resposta.data[0].nome);

        }).fail(function(jqXHR, textStatus ) {
            console.log("Request failed: " + textStatus);

        }).always(function() {
            console.log("completou");
        });
    });
</script>