<h3>Categorias</h3>
<hr>
<a class="btn btn-primary btn-primary" data-toggle="modal" data-target="#cadastrarModal" data-whatever="Nova"><span class="glyphicon glyphicon-plus"></span> Cadastrar Categoria</a>
<br><br>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Despesas</div>
            <table class="table table-hover">
                <tr>
                    <td style="width:90%">Lazer</td>
                    <td>            
                        <button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#cadastrarModal" data-whatever="Editar">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </button>
                    </td>
                    <td>
                        <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </td>
                </tr>
                <tr>
                    <td style="width:90%">Contas</td>
                    <td>
                        <button class="btn btn-primary btn-xs" data-toggle="modal" data-target="#cadastrarModal" data-whatever="Editar">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </button>                        
                    </td>
                    <td>
                        <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" >
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">Receitas</div>
            <table class="table table-hover">

            </table>
        </div>
    </div>
</div>

<?php include_once "cadastrar.phtml"?>